version: '3.6'

services:
    rest:
        build: ./rest
        ports:
            - "9090:8080"
        volumes:
            - ./rest:/rest
            #- "${HOME}/.m2:/root/.m2" 
    etl:
        build: ./etl
        ports:
            - "9091:8080"
        volumes:
            - ./etl:/etl
            #- "${HOME}/.m2:/root/.m2" 
        depends_on:
            - db
            - rest
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: work_shifts
            MYSQL_USER: smartcat
            MYSQL_PASSWORD: smartcat
        ports:
            - "3306:3306"
    
        volumes:
            - ./init:/docker-entrypoint-initdb.d

    adminer:
        image: adminer
        restart: always
        ports: 
            - 9092:8080
